[package]
name = "rs-sampler"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"
del-raycast-core= {  path = "../del-raycast/del-raycast-core" }

[dev-dependencies]
rand = "0.8"
